### ISSUE TITLE
Compilation failed due to incorrect method name

### ISSUE THREAD

**Issue by CatHood0** [VisualSystemsCorp/vsc_quill_delta_to_html#12]
```
../../../.pub-cache/hosted/pub.dev/vsc_quill_delta_to_html-1.0.3/lib/src/quill_delta_to_html_converter.dart:264:22: Error: The method 'mapIndexed' isn't defined for the class 'List<DeltaInsertOp>'.
 - 'List' is from 'dart:core'.
 - 'DeltaInsertOp' is from 'package:vsc_quill_delta_to_html/src/delta_insert_op.dart' ('../../../.pub-cache/hosted/pub.dev/vsc_quill_delta_to_html-1.0.3/lib/src/delta_insert_op.dart').
Try correcting the name to the name of an existing method, or defining a method named 'mapIndexed'.
    final html = ops.mapIndexed((i, op) {
                     ^^^^^^^^^^
```

**Comment by dsyrstad** [comment]
The example app builds and runs for me.

`mapIndexed()` is an extension method on List from the `collection` package, which vsc_quill_delta_to_html depends on. I'm wondering if maybe you've overridden the version? Can you include your pubspec.yaml?

**Comment by CatHood0** [comment]
This appears only when i trying to test the converter, but throw that error. I'm using the default version from the **pub.dev**

Here are my dependencies:
```
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  random_name_generator: ^1.2.0
  flutter_colorpicker: ^1.0.3
  permission_handler: ^11.0.0
  flutter_slidable: ^3.0.0
  device_info_plus: ^9.0.3
  number_to_string: ^0.0.3
  appflowy_editor: ^2.0.0 
  timeline_tile: ^2.0.0
  flutter_quill: ^8.6.0
  path_provider: ^2.0.15
  open_file: ^3.3.2
  motion_toast: ^2.7.8
  filesaverz: ^3.1.0
  icons_plus: ^4.0.0
  pdf_render: ^1.4.0
  numerus: ^2.1.2
  get_it: ^7.6.4
  path: ^1.8.3
  intl: ^0.18.1
  http: ^1.1.0
  uuid: ^4.2.1
  flutter_riverpod: ^2.3.7
  hooks_riverpod: ^2.4.6
  flutter_hooks: ^0.20.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  objectbox: 2.3.1
  objectbox_flutter_libs: 2.3.1

  vsc_quill_delta_to_html: ^1.0.3

  docx_template: ^0.4.0
  html2md: ^1.3.1
  pdf: ^3.10.6
  shared_preferences: ^2.1.1
  dio: ^5.3.2
  mocktail: ^1.0.0
  keyboard_height_plugin: ^0.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  objectbox_generator: 2.3.1
  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1
```
